const fetchImagesButton=document.getElementById('fetchImagesButton');const downloadButton=document.getElementById('downloadButton');const selectAllButton=document.getElementById('selectAllButton');let inputUrl='';function showProcessingLabel(){const processingLabel=document.getElementById('processingLabel');processingLabel.style.display='block'}
function hideProcessingLabel(){const processingLabel=document.getElementById('processingLabel');processingLabel.style.display='none'}
function fetchImageLinks(url){const proxyUrl='https://cors-anywhere.herokuapp.com/';return fetch(proxyUrl+url).then(response=>response.text()).then(data=>{const tempDiv=document.createElement('div');tempDiv.innerHTML=data;const images=tempDiv.querySelectorAll('.owl-carousel.owl-theme .item img');let imageLinks=[];images.forEach((img)=>{let src=img.getAttribute('src');if(src&&src.startsWith('http')){imageLinks.push(src)}});return imageLinks}).catch(error=>{console.error('Error fetching page:',error);return[]})}
function fetchImages(){inputUrl=document.getElementById('inputUrl').value.trim();if(inputUrl===''){alert('Masukkan link gambar atau halaman terlebih dahulu.');return}
fetchImagesButton.disabled=!0;fetchImagesButton.style.backgroundColor='#ccc';fetchImagesButton.textContent='Loading...';showProcessingLabel();const imageContainer=document.getElementById('imageContainer');imageContainer.innerHTML='';fetchImageLinks(inputUrl).then(imageLinks=>{if(imageLinks.length>0){downloadButton.style.display='block';selectAllButton.style.display='block';selectAllButton.textContent='Select All'}
imageContainer.innerHTML='';const rowDiv=document.createElement('div');rowDiv.classList.add('row','row-cols-2','row-cols-md-6','g-4');imageLinks.forEach((link,index)=>{console.log(`${index + 1}. ${link}`);const colDiv=document.createElement('div');colDiv.classList.add('col');const cardDiv=document.createElement('div');cardDiv.classList.add('card');const imageItem=document.createElement('div');imageItem.classList.add('image-item');const imgElement=document.createElement('img');imgElement.src=link;imgElement.alt=`Image ${index + 1}`;imgElement.classList.add('card-img-top');imageItem.appendChild(imgElement);const checkboxContainer=document.createElement('div');checkboxContainer.classList.add('checkbox-container');const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.dataset.link=link;checkboxContainer.appendChild(checkbox);imageItem.appendChild(checkboxContainer);cardDiv.appendChild(imageItem);colDiv.appendChild(cardDiv);rowDiv.appendChild(colDiv)});imageContainer.appendChild(rowDiv);hideProcessingLabel();fetchImagesButton.disabled=!1;fetchImagesButton.style.backgroundColor='#007bff';fetchImagesButton.textContent='Fetch Images'})}
function toggleSelectAll(){const checkboxes=document.querySelectorAll('#imageContainer input[type="checkbox"]');const selectAllButton=document.getElementById('selectAllButton');if(selectAllButton.textContent==='Select All'){checkboxes.forEach(checkbox=>{checkbox.checked=!0});selectAllButton.textContent='Disselect'}else{checkboxes.forEach(checkbox=>{checkbox.checked=!1});selectAllButton.textContent='Select All'}}
function downloadImages(){downloadButton.disabled=!0;downloadButton.style.backgroundColor='#ccc';downloadButton.textContent='Loading...';const imageContainer=document.getElementById('imageContainer');const checkboxes=imageContainer.querySelectorAll('input[type="checkbox"]:checked');if(checkboxes.length===0){alert('Tidak ada gambar yang dipilih untuk diunduh.');downloadButton.disabled=!1;downloadButton.style.backgroundColor='#007bff';downloadButton.textContent='Download Images';return}
const zip=new JSZip();const proxyUrl='https://cors-anywhere.herokuapp.com/';const promises=[];checkboxes.forEach((checkbox,index)=>{const url=checkbox.dataset.link;const filename=`image${index + 1}.jpg`;const promise=fetch(proxyUrl+url).then(response=>response.blob()).then(blob=>{zip.file(filename,blob)});promises.push(promise)});Promise.all(promises).then(()=>{zip.generateAsync({type:'blob'}).then(content=>{const fileName=getFileNameFromUrl(inputUrl);saveAs(content,`${fileName}.zip`);downloadButton.disabled=!1;downloadButton.style.backgroundColor='#007bff';downloadButton.textContent='Download Images'})})}
function getFileNameFromUrl(url){return url.substring(url.lastIndexOf('/')+1)}